AddHandler, AddressOf, Alias, And, AndAlso, As, Boolean, ByRef, ByVal, Call, Case, Catch,
CBool, CByte, CChar, CDate, CDec, CDbl, Char, CInt, Class, CLng, CObj, Const,
Continue, CSByte, CShort, CStr, CultureInfo, CustomAttribute, DateTime,
Delegate, Dim, DirectCast, Do, Double, Each, Else, ElseIf, End,
Enum, Emit, Exit, False, Finally, For, Friend, Function, Get, GetType,
Global, GoTo, Handles, If, Implements, Imports, In, Inherits,
Interface, Is, IsNot, Join, Keyword, Let, Lib, Like, LineInfo,
Long, Loop, Me, Mod, Module, MustInherit, MustOverride, MyBase,
MyClass, NameOf, Native, NegativeInfinity, NeutralResourcesLanguage,
New, Next, No, Nullable, Object, Occurred, Off, On,
Open, Option, Or, OrElse, Overloads, Overridable, Override,
ParamArray, Partial, Parallel, Parsing, PascalCase,
Private, Properties, Protected, Public, ReadOnly, ReDim, Real,
References, Reflection, Remaining, RemoveHandler, Resume, Return,
SByte, Sealed, Select, Sending, Send, Separated, Serializable,
Server, Set, Shared, Short, Shutdown, Single, Signed,
SinglyLinkedList, SlidingWindowDelimiter, Smallest, SortedList,
Sorting, SortOrder, SoundPlayer, Split, Splitting, SQL, StackTrace,
Statements, Status, Step, Stop, StreamReader, StreamWriter,
String, Struct, Sub, Synchronized, SyntaxTree, Take,
TargetInvocationException, Task, TemplateAlias, Test, Text,
Then, This, Thread, Throws, Timeout, Timestamp, ToArray,
ToString, Tracing, TransparentProxy, True, Try, TryCast,
Trying, TypedReference, TypeOf, UltraLargeNumber, Unchecked,
UnhandledException, Unicode, Union, Unity, UniversalContainer,
Until, Up, Using, UserState, UTF, Values, Variance, VarKeyword,
Variant, Virtual, Visibility, Volatile, WaitHandle, WebRequest,
When, Where, Whole, Windows, WinForms, Wrapper, XMLNameSpace,
Yield, Zero
